/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package server;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ClientStatus { 
  LOBBY, PUBLIC, PRIVATE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ClientStatus\",\"namespace\":\"server\",\"symbols\":[\"LOBBY\",\"PUBLIC\",\"PRIVATE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
