/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package chat_app;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface AppClientInterface {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"AppClientInterface\",\"namespace\":\"chat_app\",\"types\":[],\"messages\":{\"receiveMessage\":{\"request\":[{\"name\":\"message\",\"type\":\"string\"}],\"response\":\"int\"},\"receiveRequest\":{\"request\":[{\"name\":\"request\",\"type\":\"string\"}],\"response\":\"int\"},\"setPrivateChatClient\":{\"request\":[{\"name\":\"username\",\"type\":\"string\"},{\"name\":\"ipaddress\",\"type\":\"string\"},{\"name\":\"port\",\"type\":\"int\"}],\"response\":\"int\"},\"startPrivateChat\":{\"request\":[],\"response\":\"int\"},\"stopPrivateChat\":{\"request\":[],\"response\":\"int\"},\"video\":{\"request\":[{\"name\":\"iets\",\"type\":\"string\"}],\"response\":\"string\"}}}");
  int receiveMessage(java.lang.CharSequence message) throws org.apache.avro.AvroRemoteException;
  int receiveRequest(java.lang.CharSequence request) throws org.apache.avro.AvroRemoteException;
  int setPrivateChatClient(java.lang.CharSequence username, java.lang.CharSequence ipaddress, int port) throws org.apache.avro.AvroRemoteException;
  int startPrivateChat() throws org.apache.avro.AvroRemoteException;
  int stopPrivateChat() throws org.apache.avro.AvroRemoteException;
  java.lang.CharSequence video(java.lang.CharSequence iets) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends AppClientInterface {
    public static final org.apache.avro.Protocol PROTOCOL = chat_app.AppClientInterface.PROTOCOL;
    void receiveMessage(java.lang.CharSequence message, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void receiveRequest(java.lang.CharSequence request, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void setPrivateChatClient(java.lang.CharSequence username, java.lang.CharSequence ipaddress, int port, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void startPrivateChat(org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void stopPrivateChat(org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void video(java.lang.CharSequence iets, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
  }
}