/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package chat_app;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface ClientInterface {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"ClientInterface\",\"namespace\":\"chat_app\",\"types\":[],\"messages\":{\"recieveMessage\":{\"request\":[{\"name\":\"username\",\"type\":\"string\"},{\"name\":\"ipaddress\",\"type\":\"string\"}],\"response\":\"int\"}}}");
  int recieveMessage(java.lang.CharSequence username, java.lang.CharSequence ipaddress) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends ClientInterface {
    public static final org.apache.avro.Protocol PROTOCOL = chat_app.ClientInterface.PROTOCOL;
    void recieveMessage(java.lang.CharSequence username, java.lang.CharSequence ipaddress, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
  }
}